# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Easybuy' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for Easybuy

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'BoringSSL-GRPC', '= 0.0.3', :modular_headers => false
  pod 'gRPC-Core', '= 1.21.0', :modular_headers => false
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

end
